Completed first version of working RNAmigos endpoint
TeamW-P/RNAmigos pull request #3
Opened 2021-03-03 18:19 UTC by 1jayyaj1

Tested with the json output from BP2. Output format might need to be updated once we know front-end team requirements.

2021-03-03 22:57 UTC, ajaypatel24 approved these changes

2021-03-04 06:06 UTC, rayanosseiran commented
LGTM, but @larakollokian , thoughts on ditching route.py? would it be better to keep it for consistency across projects?

2021-03-05 17:35 UTC, rayanosseiran requested changes
For consistency, could you return an error instead of blank output and raising exceptions? 

 `return {"error": "Sample"}, 400`


For some reason, abort will result in the erorr being printed as 400: 400: error on the pipeline side so directly returning with a status code works better.

2021-03-06 07:45 UTC, larakollokian commented
> thoughts on ditching route.py? would it be better to keep it for consistency across projects

Ya I agree, i think we should keep `routes.py` to keep it consistent with the other stuff. It also adds a layer of separation from the rest of the logic and looks cleaner imo

2021-03-06 08:00 UTC, larakollokian requested changes
Overall this looks good, but I'm not really a fan of the structure of everything. 

1. I'm not sure why you got rid of the routing folder/file, but I think it would look cleaner if you put it back and put the routes there.
2. there are a lot of files at the root level that are related to the "business logic" of migos, and I think they should all be in a `core/` or `src/` folder instead. I'm talking about `fp2lig.py`, `nx2fp.py`, etc. You should have all the migos logic in a core/src folder, the routing in a `routes/` folder, and the root should have like config stuff, dockerfile and `app.py`. And app.py should be mostly empty, to keep it consistent with the other applications as well.
3. This isn't necessarily something that you should address in this PR, but I think it would be nice if we had more intuitive filenames and better comments for some of the modules. "fp2lig" doesn't really mean anything unless someone took the time to understand the code in detail. Maybe we should discuss this with Carlos and see what he thinks? Lemme know your thoughts.

2021-03-06 08:00 UTC, larakollokian commented on app.py
> +def rnamigos():
like @rayanosseiran mentionned, the routing should be done in `/routes/routes.py` to keep it consistent with BP2 and VeRNAl. It keeps all the layers separate and it just looks cleaner

2021-03-06 08:00 UTC, larakollokian commented on app.py
> +def rnamigos():
same as below v

2021-03-06 08:00 UTC, larakollokian commented on rnamigos_launcher.py
> +def launch(G, library_path, n_hits=30):
maybe add more comments here, because it's a bit unclear on what this does at a first glance

2021-03-09 22:46 UTC, merged